export const REQUEST_PROJECTS_PENDING = "REQUEST_PROJECTS_PENDING";
export const REQUEST_PROJECTS_SUCCESS = "REQUEST_PROJECTS_SUCCESS";
export const REQUEST_PROJECTS_FAILED = "REQUEST_PROJECTS_FAILED";

export const SEND_MESSAGE_PENDING = "SEND_MESSAGE_PENDING";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";

export const CLEAR_MESSAGE_STATE = "CLEAR_MESSAGE_STATE";
