export const REQUEST_PROJECTS_PENDING = "REQUEST_PROJECTS_PENDING";
export const REQUEST_PROJECTS_SUCCESS = "REQUEST_PROJECTS_SUCCESS";
export const REQUEST_PROJECTS_FAILED = "REQUEST_PROJECTS_FAILED";
